version: '3.9'
# https://hub.docker.com/_/php
# https://hub.docker.com/_/nginx

services:
  php-fpm:
    container_name: c_php
    image: php8.1-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
      - ../:/var/www/html
    networks:
      - server1_networks

  mysql: #host=mysql user=root pass=root
    container_name: c_mysql
    image: mysql:latest
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - server1_networks

  nginx:
    container_name: c_nginx
    image: nginx:latest
    ports:
      - '8021:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    links:
      - php-fpm
    networks:
      - server1_networks

  pma:
    container_name: c_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    healthcheck:
      interval: 120ms
      retries: 5
      start_period: 60ms
      test: |
        touch /tmp/healthcheck.txt &&
        mkdir /tmp/healthcheck &&
        mv /tmp/healthcheck.txt /tmp/healthcheck &&
        cd /tmp/healthcheck &&
        echo "hello my docker container is working fine" >> healthcheck.txt &&
        cat healthcheck.txt &&
        rm healthcheck.txt &&
        cd .. &&
        rmdir /tmp/healthcheck
        cls
      timeout: 30ms
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8025:80
    depends_on:
      - mysql
    volumes:
      - pma-data:/var/lib/phpmyadmin/data
    networks:
      - server1_networks

  adminer:
    container_name: c_adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports:
      - 8026:8080
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
    networks:
      - server1_networks

volumes:
  mysql-data: #volumes in service
  pma-data:
networks:
  server1_networks:
